// <auto-generated />
using API_GESTION_CONOCIMIENTO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_GESTION_CONOCIMIENTO.Migrations
{
    [DbContext(typeof(GestionConocimientoDbContext))]
    [Migration("20241226174705_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_GESTION_CONOCIMIENTO.Models.Enfermedad", b =>
                {
                    b.Property<int>("IdEnfermedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnfermedad"));

                    b.Property<string>("NombreE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnfermedad");

                    b.ToTable("Enfermedades");
                });

            modelBuilder.Entity("API_GESTION_CONOCIMIENTO.Models.Medicamento", b =>
                {
                    b.Property<int>("IdMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamento"));

                    b.Property<string>("NombreM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedicamento");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("API_GESTION_CONOCIMIENTO.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<string>("NombreT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTratamiento");

                    b.ToTable("Tratamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
